title: "Data With Michael"
description: "My Data Engineering Portfolio and Blog"
theme: minima
show_excerpts: true
markdown: kramdown

# Optional navigation links
nav:
  - name: "Home"
    link: "/"
  - name: "Projects"
    link: "/projects.html"
  - name: "Blog"
    link: "/blog.html"
  - name: "About"
    link: "/about.html"
